{{ if .Values.operator.createOperatorServiceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ include "mongodb-kubernetes-operator.namespace" . }}
{{- if .Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ .Values.registry.imagePullSecrets }}
{{- end }}
{{- end }} {{/* if .Values.operator.createOperatorServiceAccount */}}
