{{ if .Values.operator.createOperatorServiceAccount }}
{{ if .Values.operator.enablePVCResize }}

{{- $watchNamespace := include "mongodb-kubernetes-operator.namespace" . | list }}
{{- if .Values.operator.watchNamespace }}
{{- $watchNamespace = regexSplit "," .Values.operator.watchNamespace -1 }}
{{- $watchNamespace = concat $watchNamespace (include "mongodb-kubernetes-operator.namespace" . | list) | uniq }}
{{- end }}


{{- $roleScope := "Role" -}}
{{- if or (gt (len $watchNamespace) 1) (eq (first $watchNamespace) "*") }}
{{- $roleScope = "ClusterRole" }}
{{- end }}
---
kind: {{ $roleScope }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}-pvc-resize
{{- if eq $roleScope "Role" }}
  namespace: {{ include "mongodb-kubernetes-operator.namespace" . }}
{{- end }}
rules:
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - delete
      - list
      - watch
      - patch
      - update
{{- range $idx, $namespace := $watchNamespace }}

{{- $namespaceBlock := "" }}
{{- if not (eq $namespace "*") }}
{{- $namespaceBlock = printf "namespace: %s" $namespace }}
{{- end }}

---
{{- if eq $namespace "*" }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Values.operator.name }}-pvc-resize-binding
  {{ $namespaceBlock }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ $roleScope }}
  name: {{ $.Values.operator.name }}-pvc-resize
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.operator.name }}
    namespace: {{ include "mongodb-kubernetes-operator.namespace" $ }}
{{- end }}

{{- end}}{{/* if .Values.operator.enablePVCResize */}}
{{- end}}{{/* if .Values.operator.createOperatorServiceAccount */}}
