{{- $clusterRoleName := printf "%s-cluster-telemetry" .Values.operator.name }}
{{- $telemetry := default dict .Values.operator.telemetry }}

{{/* We can't use default here, as 0, false and nil as determined as unset and thus set the default value */}}
{{- if ne $telemetry.enabled false }}
  {{- if ne $telemetry.installClusterRole false}}

---
# Additional ClusterRole for clusterVersionDetection
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $clusterRoleName }}
rules:
  # Non-resource URL permissions
  - nonResourceURLs:
      - "/version"
    verbs:
      - get
  # Cluster-scoped resource permissions
  - apiGroups:
      - ''
    resources:
      - namespaces
    resourceNames:
      - kube-system
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - list
---
# ClusterRoleBinding for clusterVersionDetection
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.operator.name }}-{{ include "mongodb-kubernetes-operator.namespace" . }}-cluster-telemetry-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $clusterRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.name }}
    namespace: {{ include "mongodb-kubernetes-operator.namespace" . }}
  {{- end}}{{/* if ne $telemetry.installClusterRole false */}}
{{- end }}{{/* if ne $telemetry.enabled false */}}
