apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mongodb-atlas-operator.name" . }}
  labels:
    {{- include "mongodb-atlas-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mongodb-atlas-operator.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mongodb-atlas-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mongodb-atlas-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 10
      containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        - name: manager
          args:
            - --atlas-domain={{ .Values.atlasURI }}
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
            - --leader-elect
          command:
            - /manager
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.watchNamespaces }}
          - name: WATCH_NAMESPACE
            value: "{{- .Values.watchNamespaces }}"
          {{- end }}
          {{- if .Values.disableAtlasClusterReconciler }}
          - name: DISABLE_ATLAS_CLUSTER_RECONCILER
            value: "{{- .Values.disableAtlasClusterReconciler }}"
          {{- end }}
          {{- if .Values.disableAtlasProjectReconciler }}
          - name: DISABLE_ATLAS_PROJECT_RECONCILER
            value: "{{- .Values.disableAtlasProjectReconciler }}"
          {{- end }}
          {{- if .Values.disableAtlasDatabaseUserReconciler }}
          - name: DISABLE_ATLAS_DATABASE_USER_RECONCILER
            value: "{{- .Values.disableAtlasDatabaseUserReconciler }}"
          {{- end }}
          - name: OPERATOR_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
