apiVersion: v2
name: community-operator-crds
description: MongoDB Kubernetes Community Operator - CRDs
type: application
version: 0.8.3
appVersion: 0.8.3
kubeVersion: '>=1.16-0'
keywords:
- mongodb
- database
- nosql
icon: https://mongodb-images-new.s3.eu-west-1.amazonaws.com/leaf-green-dark.png
home: https://github.com/mongodb/mongodb-kubernetes-operator
maintainers:
- name: MongoDB
  email: support@mongodb.com
