---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  members: 3
  type: ReplicaSet
  version: "{{ .Values.mongodbVersion }}"
  security:
    authentication:
      modes: ["SCRAM"]
  users:
    - name: {{ .Values.mongodbUsername }} 
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: {{ .Release.Name }}-mongodb-user-password
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
      scramCredentialsSecretName: {{ .Release.Name }}-mongodb-scram-salt
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib

