## Operator

# Set this to true if your cluster is managing SecurityContext for you.
# If running OpenShift (Cloud, Minishift, etc.), set this to true.
managedSecurityContext: false

operator:
  # Execution environment for the operator, dev or prod. Use dev for more verbose logging
  env: prod

  # Default architecture for the operator.
  # Values are "static" and "non-static:
  mdbDefaultArchitecture: non-static

  # Name that will be assigned to most internal Kubernetes objects like Deployment, ServiceAccount, Role etc.
  name: mongodb-enterprise-operator-multi-cluster

  # Name of the operator image
  operator_image_name: mongodb-enterprise-operator-ubi

  # Name of the deployment of the operator pod
  deployment_name: mongodb-enterprise-operator

  # Version of mongodb-enterprise-operator
  version: 1.25.0

  # The Custom Resources that will be watched by the Operator. Needs to be changed if only some of the CRDs are installed
  watchedResources:
    - mongodb
    - opsmanagers
    - mongodbusers

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # operator cpu requests and limits
  resources:
    requests:
      cpu: 500m
      memory: 200Mi
    limits:
      cpu: 1100m
      memory: 1Gi

  # Create operator service account and roles
  # if false, then templates/operator-roles.yaml is excluded
  createOperatorServiceAccount: true

  vaultSecretBackend:
    # set to true if you want the operator to store secrets in Vault
    enabled: false
    tlsSecretRef: ""

  replicas: 1

## Database
database:
  name: mongodb-enterprise-database-ubi
  version: 1.25.0

initDatabase:
  name: mongodb-enterprise-init-database-ubi
  version: 1.25.0

## Ops Manager
opsManager:
  name: mongodb-enterprise-ops-manager-ubi

initOpsManager:
  name: mongodb-enterprise-init-ops-manager-ubi
  version: 1.25.0

## Application Database
initAppDb:
  name: mongodb-enterprise-init-appdb-ubi
  version: 1.25.0

agent:
  name: mongodb-agent-ubi
  version: 12.0.29.7785-1

mongodbLegacyAppDb:
  name: mongodb-enterprise-appdb-database-ubi
  repo: quay.io/mongodb

mongodb:
  name: mongodb-enterprise-server
  repo: quay.io/mongodb
  appdbAssumeOldFormat: false
  imageType: ubi8

## Registry
registry:
  imagePullSecrets:
  pullPolicy: Always
  # Specify if images are pulled from private registry
  operator: quay.io/mongodb
  database: quay.io/mongodb
  initDatabase: quay.io/mongodb
  initOpsManager: quay.io/mongodb
  opsManager: quay.io/mongodb
  initAppDb: quay.io/mongodb
  appDb: quay.io/mongodb
  agent: quay.io/mongodb
  agentRepository: quay.io/mongodb/mongodb-agent-ubi

multiCluster:
  # Specify if we want to deploy the operator in multi-cluster mode
  clusters:
    [
      "MDB_CLUSTER_1_FULL_NAME",
      "MDB_CLUSTER_2_FULL_NAME",
      "MDB_CLUSTER_3_FULL_NAME",
    ]
  kubeConfigSecretName: mongodb-enterprise-operator-multi-cluster-kubeconfig
  performFailOver: true
  clusterClientTimeout: 10
# Set this to false to disable subresource utilization
# It might be required on some versions of Openshift
subresourceEnabled: true
