{{- if .Values.project.create }}
{{- range .Values.users }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atlas-cluster.fullname" $ }}-{{ .username }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "atlas-cluster.labels" $ | nindent 4 }}
type: Opaque
stringData:
  password: {{ .password | default (randAlphaNum 32 | b64enc)| quote }}
{{- end }}
{{- end }}
