{{ if .Values.operator.createResourcesServiceAccountsAndRoles }}

{{- $watchNamespace := include "mongodb-kubernetes-operator.namespace" . | list }}
{{- if .Values.operator.watchNamespace }}
{{- $watchNamespace = regexSplit "," .Values.operator.watchNamespace -1 }}
{{- end }}


{{- range $idx, $namespace := $watchNamespace }}

{{- $namespaceBlock := printf "namespace: %s" $namespace }}
{{- if eq $namespace "*" }}
{{- $namespaceBlock = include "mongodb-kubernetes-operator.namespace" $ | printf "namespace: %s"  }}
{{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.operator.baseName }}-appdb
  {{ $namespaceBlock }}
{{- if $.Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ $.Values.registry.imagePullSecrets }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.operator.baseName }}-database-pods
  {{ $namespaceBlock }}
{{- if $.Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ $.Values.registry.imagePullSecrets }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.operator.baseName }}-ops-manager
  {{ $namespaceBlock }}
{{- if $.Values.registry.imagePullSecrets}}
imagePullSecrets:
  - name: {{ $.Values.registry.imagePullSecrets }}
{{- end }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $.Values.operator.baseName }}-appdb
  {{ $namespaceBlock }}
rules:
  - apiGroups:
      - ''
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{$.Values.operator.baseName}}-appdb
  {{ $namespaceBlock }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{$.Values.operator.baseName}}-appdb
subjects:
  - kind: ServiceAccount
    name: {{$.Values.operator.baseName}}-appdb
    {{ $namespaceBlock }}

{{- end }}
{{- end }}{{/* if .Values.operator.createResourcesServiceAccountsAndRoles */}}
