{{- $databaseNamespaces := include "community-operator.database.namespaces" . | fromYamlArray }}
{{- $databaseName := $.Values.database.name }}
{{- range $namespace := $databaseNamespaces }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $databaseName }}
  namespace: {{ $namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $databaseName }}
  namespace: {{ $namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - patch
      - delete
      - get

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $databaseName }}
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ $databaseName }}
roleRef:
  kind: Role
  name: {{ $databaseName }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}