---
mongodb:
  type: ReplicaSet
  members: 3
  version: 5.0.4

  authentication:
    - SCRAM
    - X509
    - LDAP

  # These values will be used if `mongodb.type` is "ShardedCluster".
  # For more information about these values please visit:
  # https://docs.mongodb.com/kubernetes-operator/stable/reference/k8s-operator-specification
  sharding:
    shardCount: 2
    mongodsPerShardCount: 3
    mongosCount: 2
    configServerCount: 3

manager:
  # Corresponds to `spec.opsManager.configMapRef.name`
  # More info: https://docs.mongodb.com/kubernetes-operator/stable/reference/k8s-operator-specification/#spec.opsManager.configMapRef.name
  configMapRef: my-project

  # Corresponds to `spec.credentials`
  # More info: https://docs.mongodb.com/kubernetes-operator/stable/reference/k8s-operator-specification/#spec.credentials
  credentials: my-credentials

backup:
  mode: disabled

podSpec:
  # This is a corev1.PodTemplate resource structure that will be used
  # by the Operator to override the default configuration for Pods in the
  # StatefulSets.
  podTemplate:
    spec:
      containers:
        - name: mongodb-enterprise-database
          # For more information about Pod and container resource management, see:
          # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          resources:
            limits:
              cpu: "0.25"
              memory: 512M

  persistence:
    multiple:
      data:
        storage: 10Gi
      journal:
        storage: 1Gi
      logs:
        storage: 500M

# The following attributes allow you to change the configuration of a
# MongoDB Sharded Cluster.
# Find more information about Sharded Clusters here:
# - https://docs.mongodb.com/manual/core/sharded-cluster-components/
#
# You can learn about these attributes and how the change the structure
# of your Sharded Cluster in here:
# - https://docs.mongodb.com/kubernetes-operator/stable/reference/k8s-operator-specification
configSrvPodSpec: {}

shardPodSpec: {}

mongosPodSpec: {}
