mongodb-atlas-operator-crds:
  enabled: true

# atlasURI is the URI of the MongoDB Atlas
atlasURI: https://cloud.mongodb.com

# globalConnectionSecret is a default "global" Secret containing Atlas authentication information
# It is used if the project-level connection Secret is not provided.
# It's not recommended to check-in these values as part of values.yaml file to the VCS -
# try using '--set' operator instead, for example '--set globalConnectionSecret.orgId=<id>'
globalConnectionSecret:
  orgId: ""
  publicApiKey: ""
  privateApiKey: ""

# watchNamespaces is the set of namespaces that are watched by the Operator.
# The only possible values are:
# - empty (watch all namespaces) or
# - the name of the same namespace where the Operator is installed to.
watchNamespaces: ""

# Allow to granularly disable reconcilers. Uncomment to disable
# disableAtlasClusterReconciler: "true"
# disableAtlasProjectReconciler: "true"
# disableAtlasDatabaseUserReconciler: "true"

image:
  repository: mongodb/mongodb-atlas-kubernetes-operator
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 2000

securityContext:
  allowPrivilegeEscalation: false

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 50Mi

nodeSelector: {}

tolerations: []

affinity: {}
