---
replicaCount: 1

image:
  frontend:
    repository: quay.io/mongodb/farm-intro-frontend
  backend:
    repository: quay.io/mongodb/farm-intro-backend
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port:
    backend: 8000
    frontend: 3000


mongodb:
  # Set this value to the name of the Secret created by any of
  # the MongoDB Operators, containing the `connectionString.standardSrv`
  # attribute, used to connect to MongoDB.
  #
  # The Secret's name will always be:
  #
  # - <resource-name>-<database>-<user>
  #
  # In the same namespace that the resource was created.
  connectionStringSecret: "<resource-name>-<database>-<user>"

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: sample-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: sample-app-tls
  #    hosts:
  #      - sample-app.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
