name: Bashscript linter

on:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: bewuethr/shellcheck-action@v2
