name: "Helm Chart Releaser"
description: "Host a Helm charts repo on GitHub Pages"
inputs:
  version:
    description: "The chart-releaser version to use (default: v1.2.1)"
    required: false
    default: v1.6.0
  work_dir:
    description: "The repo directory"
    required: false
    default: "."
  charts_repo_url:
    description: "The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)"
    required: true
  target:
    description: "Specific charts folder inside <charts_dir> for releasing"
    required: false
  dryrun:
    description: "not actually release, but check what would be done"
    required: false
  mark_latest:
    description: "mark released charts as latest"
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        export VERSION="${{ inputs.version }}"
        export WORK_DIR=${{ inputs.work_dir }}
        export CHART_DIR="charts"
        export CHARTS_REPO_URL="${{ inputs.charts_repo_url }}"
        export DRYRUN="${{ inputs.dryrun }}"
        export MARK_LATEST="${{ inputs.mark_latest }}"

        owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
        repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
        export OWNER=$owner
        export REPO=$repo

        cd $WORK_DIR && "$GITHUB_ACTION_PATH/cr.sh" "${{ inputs.target }}"
