name: "Helm Chart Releaser"
description: "Host a Helm charts repo on GitHub Pages"
inputs:
  version:
    description: "The chart-releaser version to use (default: v1.2.1)"
    required: false
    default: v1.2.1
  charts_dir:
    description: "The charts directory"
    required: false
    default: charts
  charts_repo_url:
    description: "The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)"
    required: true
  target:
    description: "Specific charts folder inside <charts_dir> for releasing"
    required: false
runs:
  using: composite
  steps:
    - run: |
        export VERSION="${{ inputs.version }}"
        export CHART_DIR="${{ inputs.charts_dir }}"
        export CHARTS_REPO_URL="${{ inputs.charts_repo_url }}"

        owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
        repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
        export OWNER=$owner
        export REPO=$repo

        mapfile -t target< <(echo ${{ inputs.target }})
        "$GITHUB_ACTION_PATH/cr.sh" "${target[@]}"
      shell: bash
